// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TesterLab.Infrastructure.Data;

#nullable disable

namespace TesterLab.Infrastructure.Migrations
{
    [DbContext(typeof(TesterLabDbContext))]
    [Migration("20260625195120_AjoutUserCreatedIdSurTestRun")]
    partial class AjoutUserCreatedIdSurTestRun
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.20");

            modelBuilder.Entity("TesterLab.Domain.Models.ActionTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Example")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ActionTemplates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Navigation",
                            Description = "Naviguer vers une page",
                            Example = "Aller à /login",
                            Icon = "🏠",
                            Name = "Aller à la page"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Interaction",
                            Description = "Cliquer sur un élément",
                            Example = "Cliquer sur le bouton Se connecter",
                            Icon = "👆",
                            Name = "Cliquer sur"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Form",
                            Description = "Remplir un champ",
                            Example = "Saisir l'email dans le champ Email",
                            Icon = "⌨️",
                            Name = "Saisir du texte"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Validation",
                            Description = "Valider un résultat",
                            Example = "Vérifier que le message Bienvenue s'affiche",
                            Icon = "✅",
                            Name = "Vérifier que"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Wait",
                            Description = "Attendre un délai",
                            Example = "Attendre 3 secondes",
                            Icon = "⏱️",
                            Name = "Attendre"
                        });
                });

            modelBuilder.Entity("TesterLab.Domain.Models.Application", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AppType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("MainUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Selected")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Applications");
                });

            modelBuilder.Entity("TesterLab.Domain.Models.Environment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccessInfo")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ApplicationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("RequiresAuth")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId", "Active")
                        .HasDatabaseName("IX_Environment_ApplicationId_Active");

                    b.ToTable("Environments");
                });

            modelBuilder.Entity("TesterLab.Domain.Models.ExecutionLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StackTrace")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("TestCaseExecutionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TestRunId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TestCaseExecutionId");

                    b.HasIndex("TestRunId");

                    b.ToTable("ExecutionLogs");
                });

            modelBuilder.Entity("TesterLab.Domain.Models.Feature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ApplicationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BusinessPriority")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Complexity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Icon")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.ToTable("Features");
                });

            modelBuilder.Entity("TesterLab.Domain.Models.Job", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConsecutiveFailures")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("EnvironmentId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FrequencyInMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRunning")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastExecutionStatus")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastExecutionTimeUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NextExecutionTimeUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("TestCaseId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("TesterLab.Domain.Models.PerformanceMetric", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Context")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MetricName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TestCaseExecutionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TestRunId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<double>("Value")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("TestCaseExecutionId");

                    b.HasIndex("TestRunId");

                    b.ToTable("PerformanceMetrics");
                });

            modelBuilder.Entity("TesterLab.Domain.Models.Screenshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CapturedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TestCaseExecutionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TestRunId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TestStepExecutionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TestCaseExecutionId");

                    b.HasIndex("TestRunId");

                    b.HasIndex("TestStepExecutionId");

                    b.ToTable("Screenshots");
                });

            modelBuilder.Entity("TesterLab.Domain.Models.SystemSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEncrypted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("SystemSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "General",
                            DataType = "String",
                            Description = "Nom de l'application",
                            IsEncrypted = false,
                            Key = "General.ApplicationName",
                            UpdatedAt = new DateTime(2026, 6, 25, 19, 51, 20, 303, DateTimeKind.Utc).AddTicks(1463),
                            Value = "TesterLab"
                        },
                        new
                        {
                            Id = 2,
                            Category = "General",
                            DataType = "String",
                            IsEncrypted = false,
                            Key = "General.BaseUrl",
                            UpdatedAt = new DateTime(2026, 6, 25, 19, 51, 20, 303, DateTimeKind.Utc).AddTicks(1469),
                            Value = "http://localhost"
                        },
                        new
                        {
                            Id = 3,
                            Category = "General",
                            DataType = "String",
                            IsEncrypted = false,
                            Key = "General.TimeZone",
                            UpdatedAt = new DateTime(2026, 6, 25, 19, 51, 20, 303, DateTimeKind.Utc).AddTicks(1470),
                            Value = "UTC"
                        },
                        new
                        {
                            Id = 4,
                            Category = "General",
                            DataType = "String",
                            IsEncrypted = false,
                            Key = "General.DefaultLanguage",
                            UpdatedAt = new DateTime(2026, 6, 25, 19, 51, 20, 303, DateTimeKind.Utc).AddTicks(1472),
                            Value = "fr-FR"
                        },
                        new
                        {
                            Id = 5,
                            Category = "General",
                            DataType = "Boolean",
                            IsEncrypted = false,
                            Key = "General.MaintenanceMode",
                            UpdatedAt = new DateTime(2026, 6, 25, 19, 51, 20, 303, DateTimeKind.Utc).AddTicks(1473),
                            Value = "false"
                        },
                        new
                        {
                            Id = 6,
                            Category = "General",
                            DataType = "Boolean",
                            IsEncrypted = false,
                            Key = "General.AllowRegistration",
                            UpdatedAt = new DateTime(2026, 6, 25, 19, 51, 20, 303, DateTimeKind.Utc).AddTicks(1477),
                            Value = "true"
                        },
                        new
                        {
                            Id = 7,
                            Category = "General",
                            DataType = "Boolean",
                            IsEncrypted = false,
                            Key = "General.RequireEmailConfirmation",
                            UpdatedAt = new DateTime(2026, 6, 25, 19, 51, 20, 303, DateTimeKind.Utc).AddTicks(1478),
                            Value = "true"
                        },
                        new
                        {
                            Id = 10,
                            Category = "Email",
                            DataType = "String",
                            IsEncrypted = false,
                            Key = "Email.SmtpHost",
                            UpdatedAt = new DateTime(2026, 6, 25, 19, 51, 20, 303, DateTimeKind.Utc).AddTicks(1480),
                            Value = "smtp.gmail.com"
                        },
                        new
                        {
                            Id = 11,
                            Category = "Email",
                            DataType = "Integer",
                            IsEncrypted = false,
                            Key = "Email.SmtpPort",
                            UpdatedAt = new DateTime(2026, 6, 25, 19, 51, 20, 303, DateTimeKind.Utc).AddTicks(1481),
                            Value = "587"
                        },
                        new
                        {
                            Id = 12,
                            Category = "Email",
                            DataType = "Boolean",
                            IsEncrypted = false,
                            Key = "Email.EnableSsl",
                            UpdatedAt = new DateTime(2026, 6, 25, 19, 51, 20, 303, DateTimeKind.Utc).AddTicks(1483),
                            Value = "true"
                        },
                        new
                        {
                            Id = 13,
                            Category = "Email",
                            DataType = "String",
                            IsEncrypted = false,
                            Key = "Email.FromEmail",
                            UpdatedAt = new DateTime(2026, 6, 25, 19, 51, 20, 303, DateTimeKind.Utc).AddTicks(1484),
                            Value = "noreply@testerlab.com"
                        },
                        new
                        {
                            Id = 14,
                            Category = "Email",
                            DataType = "String",
                            IsEncrypted = false,
                            Key = "Email.FromName",
                            UpdatedAt = new DateTime(2026, 6, 25, 19, 51, 20, 303, DateTimeKind.Utc).AddTicks(1486),
                            Value = "TesterLab"
                        },
                        new
                        {
                            Id = 15,
                            Category = "Email",
                            DataType = "Boolean",
                            IsEncrypted = false,
                            Key = "Email.EmailEnabled",
                            UpdatedAt = new DateTime(2026, 6, 25, 19, 51, 20, 303, DateTimeKind.Utc).AddTicks(1487),
                            Value = "true"
                        },
                        new
                        {
                            Id = 20,
                            Category = "Testing",
                            DataType = "Integer",
                            IsEncrypted = false,
                            Key = "Testing.DefaultTimeoutSeconds",
                            UpdatedAt = new DateTime(2026, 6, 25, 19, 51, 20, 303, DateTimeKind.Utc).AddTicks(1488),
                            Value = "30"
                        },
                        new
                        {
                            Id = 21,
                            Category = "Testing",
                            DataType = "Integer",
                            IsEncrypted = false,
                            Key = "Testing.MaxRetries",
                            UpdatedAt = new DateTime(2026, 6, 25, 19, 51, 20, 303, DateTimeKind.Utc).AddTicks(1489),
                            Value = "3"
                        },
                        new
                        {
                            Id = 22,
                            Category = "Testing",
                            DataType = "String",
                            IsEncrypted = false,
                            Key = "Testing.DefaultBrowser",
                            UpdatedAt = new DateTime(2026, 6, 25, 19, 51, 20, 303, DateTimeKind.Utc).AddTicks(1491),
                            Value = "Chrome"
                        },
                        new
                        {
                            Id = 23,
                            Category = "Testing",
                            DataType = "Boolean",
                            IsEncrypted = false,
                            Key = "Testing.DefaultHeadlessMode",
                            UpdatedAt = new DateTime(2026, 6, 25, 19, 51, 20, 303, DateTimeKind.Utc).AddTicks(1492),
                            Value = "true"
                        },
                        new
                        {
                            Id = 24,
                            Category = "Testing",
                            DataType = "Boolean",
                            IsEncrypted = false,
                            Key = "Testing.CaptureScreenshotOnFailure",
                            UpdatedAt = new DateTime(2026, 6, 25, 19, 51, 20, 303, DateTimeKind.Utc).AddTicks(1527),
                            Value = "true"
                        },
                        new
                        {
                            Id = 25,
                            Category = "Testing",
                            DataType = "Boolean",
                            IsEncrypted = false,
                            Key = "Testing.CaptureScreenshotOnSuccess",
                            UpdatedAt = new DateTime(2026, 6, 25, 19, 51, 20, 303, DateTimeKind.Utc).AddTicks(1528),
                            Value = "false"
                        },
                        new
                        {
                            Id = 26,
                            Category = "Testing",
                            DataType = "Integer",
                            IsEncrypted = false,
                            Key = "Testing.RetentionDays",
                            UpdatedAt = new DateTime(2026, 6, 25, 19, 51, 20, 303, DateTimeKind.Utc).AddTicks(1530),
                            Value = "30"
                        },
                        new
                        {
                            Id = 27,
                            Category = "Testing",
                            DataType = "Integer",
                            IsEncrypted = false,
                            Key = "Testing.MaxParallelExecutions",
                            UpdatedAt = new DateTime(2026, 6, 25, 19, 51, 20, 303, DateTimeKind.Utc).AddTicks(1532),
                            Value = "5"
                        },
                        new
                        {
                            Id = 28,
                            Category = "Testing",
                            DataType = "Boolean",
                            IsEncrypted = false,
                            Key = "Testing.AutoRetryOnFailure",
                            UpdatedAt = new DateTime(2026, 6, 25, 19, 51, 20, 303, DateTimeKind.Utc).AddTicks(1533),
                            Value = "true"
                        },
                        new
                        {
                            Id = 30,
                            Category = "Security",
                            DataType = "Integer",
                            IsEncrypted = false,
                            Key = "Security.MinPasswordLength",
                            UpdatedAt = new DateTime(2026, 6, 25, 19, 51, 20, 303, DateTimeKind.Utc).AddTicks(1534),
                            Value = "12"
                        },
                        new
                        {
                            Id = 31,
                            Category = "Security",
                            DataType = "Boolean",
                            IsEncrypted = false,
                            Key = "Security.RequireUppercase",
                            UpdatedAt = new DateTime(2026, 6, 25, 19, 51, 20, 303, DateTimeKind.Utc).AddTicks(1535),
                            Value = "true"
                        },
                        new
                        {
                            Id = 32,
                            Category = "Security",
                            DataType = "Boolean",
                            IsEncrypted = false,
                            Key = "Security.RequireLowercase",
                            UpdatedAt = new DateTime(2026, 6, 25, 19, 51, 20, 303, DateTimeKind.Utc).AddTicks(1536),
                            Value = "true"
                        },
                        new
                        {
                            Id = 33,
                            Category = "Security",
                            DataType = "Boolean",
                            IsEncrypted = false,
                            Key = "Security.RequireDigit",
                            UpdatedAt = new DateTime(2026, 6, 25, 19, 51, 20, 303, DateTimeKind.Utc).AddTicks(1537),
                            Value = "true"
                        },
                        new
                        {
                            Id = 34,
                            Category = "Security",
                            DataType = "Boolean",
                            IsEncrypted = false,
                            Key = "Security.RequireNonAlphanumeric",
                            UpdatedAt = new DateTime(2026, 6, 25, 19, 51, 20, 303, DateTimeKind.Utc).AddTicks(1539),
                            Value = "true"
                        },
                        new
                        {
                            Id = 35,
                            Category = "Security",
                            DataType = "Integer",
                            IsEncrypted = false,
                            Key = "Security.MaxFailedLoginAttempts",
                            UpdatedAt = new DateTime(2026, 6, 25, 19, 51, 20, 303, DateTimeKind.Utc).AddTicks(1540),
                            Value = "5"
                        },
                        new
                        {
                            Id = 36,
                            Category = "Security",
                            DataType = "Integer",
                            IsEncrypted = false,
                            Key = "Security.LockoutDurationMinutes",
                            UpdatedAt = new DateTime(2026, 6, 25, 19, 51, 20, 303, DateTimeKind.Utc).AddTicks(1541),
                            Value = "15"
                        },
                        new
                        {
                            Id = 37,
                            Category = "Security",
                            DataType = "Integer",
                            IsEncrypted = false,
                            Key = "Security.SessionTimeoutMinutes",
                            UpdatedAt = new DateTime(2026, 6, 25, 19, 51, 20, 303, DateTimeKind.Utc).AddTicks(1542),
                            Value = "720"
                        },
                        new
                        {
                            Id = 40,
                            Category = "Branding",
                            DataType = "String",
                            IsEncrypted = false,
                            Key = "Branding.PrimaryColor",
                            UpdatedAt = new DateTime(2026, 6, 25, 19, 51, 20, 303, DateTimeKind.Utc).AddTicks(1544),
                            Value = "#007bff"
                        },
                        new
                        {
                            Id = 41,
                            Category = "Branding",
                            DataType = "String",
                            IsEncrypted = false,
                            Key = "Branding.SecondaryColor",
                            UpdatedAt = new DateTime(2026, 6, 25, 19, 51, 20, 303, DateTimeKind.Utc).AddTicks(1545),
                            Value = "#6c757d"
                        },
                        new
                        {
                            Id = 42,
                            Category = "Branding",
                            DataType = "Boolean",
                            IsEncrypted = false,
                            Key = "Branding.ShowCompanyName",
                            UpdatedAt = new DateTime(2026, 6, 25, 19, 51, 20, 303, DateTimeKind.Utc).AddTicks(1546),
                            Value = "true"
                        },
                        new
                        {
                            Id = 50,
                            Category = "Notifications",
                            DataType = "Boolean",
                            IsEncrypted = false,
                            Key = "Notifications.NotifyOnTestFailure",
                            UpdatedAt = new DateTime(2026, 6, 25, 19, 51, 20, 303, DateTimeKind.Utc).AddTicks(1551),
                            Value = "true"
                        },
                        new
                        {
                            Id = 51,
                            Category = "Notifications",
                            DataType = "Boolean",
                            IsEncrypted = false,
                            Key = "Notifications.NotifyOnTestSuccess",
                            UpdatedAt = new DateTime(2026, 6, 25, 19, 51, 20, 303, DateTimeKind.Utc).AddTicks(1552),
                            Value = "false"
                        },
                        new
                        {
                            Id = 52,
                            Category = "Notifications",
                            DataType = "Boolean",
                            IsEncrypted = false,
                            Key = "Notifications.NotifyOnScheduledRuns",
                            UpdatedAt = new DateTime(2026, 6, 25, 19, 51, 20, 303, DateTimeKind.Utc).AddTicks(1553),
                            Value = "true"
                        },
                        new
                        {
                            Id = 53,
                            Category = "Notifications",
                            DataType = "Integer",
                            IsEncrypted = false,
                            Key = "Notifications.MinSuccessRateForNotification",
                            UpdatedAt = new DateTime(2026, 6, 25, 19, 51, 20, 303, DateTimeKind.Utc).AddTicks(1554),
                            Value = "90"
                        },
                        new
                        {
                            Id = 60,
                            Category = "Storage",
                            DataType = "String",
                            IsEncrypted = false,
                            Key = "Storage.ScreenshotPath",
                            UpdatedAt = new DateTime(2026, 6, 25, 19, 51, 20, 303, DateTimeKind.Utc).AddTicks(1556),
                            Value = "wwwroot/screenshots"
                        },
                        new
                        {
                            Id = 61,
                            Category = "Storage",
                            DataType = "String",
                            IsEncrypted = false,
                            Key = "Storage.ReportsPath",
                            UpdatedAt = new DateTime(2026, 6, 25, 19, 51, 20, 303, DateTimeKind.Utc).AddTicks(1557),
                            Value = "wwwroot/reports"
                        },
                        new
                        {
                            Id = 62,
                            Category = "Storage",
                            DataType = "Integer",
                            IsEncrypted = false,
                            Key = "Storage.MaxFileSizeMB",
                            UpdatedAt = new DateTime(2026, 6, 25, 19, 51, 20, 303, DateTimeKind.Utc).AddTicks(1558),
                            Value = "10"
                        },
                        new
                        {
                            Id = 63,
                            Category = "Storage",
                            DataType = "Boolean",
                            IsEncrypted = false,
                            Key = "Storage.AutoCleanupEnabled",
                            UpdatedAt = new DateTime(2026, 6, 25, 19, 51, 20, 303, DateTimeKind.Utc).AddTicks(1559),
                            Value = "true"
                        },
                        new
                        {
                            Id = 64,
                            Category = "Storage",
                            DataType = "Integer",
                            IsEncrypted = false,
                            Key = "Storage.FileRetentionDays",
                            UpdatedAt = new DateTime(2026, 6, 25, 19, 51, 20, 303, DateTimeKind.Utc).AddTicks(1560),
                            Value = "30"
                        });
                });

            modelBuilder.Entity("TesterLab.Domain.Models.TestCase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CriticalityLevel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("EstimatedMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExecutionFrequency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FeatureId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Selected")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tags")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserPersona")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FeatureId", "Active");

                    b.ToTable("TestCases");
                });

            modelBuilder.Entity("TesterLab.Domain.Models.TestCaseExecution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorMessage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorStackTrace")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FailedSteps")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PassedSteps")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("TestCaseId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TestCaseName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("TestRunId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalSteps")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TestCaseId");

                    b.HasIndex("TestRunId");

                    b.ToTable("TestCaseExecutions");
                });

            modelBuilder.Entity("TesterLab.Domain.Models.TestData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ApplicationId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DataJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsTemplate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("SpecificEnvironmentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("SpecificEnvironmentId");

                    b.ToTable("TestDataSets");
                });

            modelBuilder.Entity("TesterLab.Domain.Models.TestRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ApplicationId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("AverageDurationMs")
                        .HasColumnType("REAL");

                    b.Property<string>("Browser")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DetailedResults")
                        .HasColumnType("TEXT");

                    b.Property<int>("EnvironmentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExecutionLogs")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExecutionType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Headless")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PassedCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProgressPercentage")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReportPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("Screenshots")
                        .HasColumnType("TEXT");

                    b.Property<int>("SkippedCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("SuccessRate")
                        .HasColumnType("REAL");

                    b.Property<string>("TargetIds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("TestDataId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Trigger")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EnvironmentId");

                    b.HasIndex("TestDataId");

                    b.HasIndex("ApplicationId", "Status");

                    b.ToTable("TestRuns");
                });

            modelBuilder.Entity("TesterLab.Domain.Models.TestStep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsOptional")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Selector")
                        .HasColumnType("TEXT");

                    b.Property<string>("Target")
                        .HasColumnType("TEXT");

                    b.Property<int>("TestCaseId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TimeoutSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TestCaseId");

                    b.ToTable("TestSteps");
                });

            modelBuilder.Entity("TesterLab.Domain.Models.TestStepExecution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorMessage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsOptional")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ScreenshotPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Selector")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("StepOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TestCaseExecutionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TestStepId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TestCaseExecutionId");

                    b.HasIndex("TestStepId");

                    b.ToTable("TestStepExecutions");
                });

            modelBuilder.Entity("TesterLab.Domain.Models.Environment", b =>
                {
                    b.HasOne("TesterLab.Domain.Models.Application", "Application")
                        .WithMany("Environments")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");
                });

            modelBuilder.Entity("TesterLab.Domain.Models.ExecutionLog", b =>
                {
                    b.HasOne("TesterLab.Domain.Models.TestCaseExecution", "TestCaseExecution")
                        .WithMany()
                        .HasForeignKey("TestCaseExecutionId");

                    b.HasOne("TesterLab.Domain.Models.TestRun", "TestRun")
                        .WithMany()
                        .HasForeignKey("TestRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TestCaseExecution");

                    b.Navigation("TestRun");
                });

            modelBuilder.Entity("TesterLab.Domain.Models.Feature", b =>
                {
                    b.HasOne("TesterLab.Domain.Models.Application", "Application")
                        .WithMany("Features")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");
                });

            modelBuilder.Entity("TesterLab.Domain.Models.PerformanceMetric", b =>
                {
                    b.HasOne("TesterLab.Domain.Models.TestCaseExecution", "TestCaseExecution")
                        .WithMany()
                        .HasForeignKey("TestCaseExecutionId");

                    b.HasOne("TesterLab.Domain.Models.TestRun", "TestRun")
                        .WithMany()
                        .HasForeignKey("TestRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TestCaseExecution");

                    b.Navigation("TestRun");
                });

            modelBuilder.Entity("TesterLab.Domain.Models.Screenshot", b =>
                {
                    b.HasOne("TesterLab.Domain.Models.TestCaseExecution", "TestCaseExecution")
                        .WithMany()
                        .HasForeignKey("TestCaseExecutionId");

                    b.HasOne("TesterLab.Domain.Models.TestRun", "TestRun")
                        .WithMany()
                        .HasForeignKey("TestRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TesterLab.Domain.Models.TestStepExecution", "TestStepExecution")
                        .WithMany()
                        .HasForeignKey("TestStepExecutionId");

                    b.Navigation("TestCaseExecution");

                    b.Navigation("TestRun");

                    b.Navigation("TestStepExecution");
                });

            modelBuilder.Entity("TesterLab.Domain.Models.TestCase", b =>
                {
                    b.HasOne("TesterLab.Domain.Models.Feature", "Feature")
                        .WithMany("TestCases")
                        .HasForeignKey("FeatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Feature");
                });

            modelBuilder.Entity("TesterLab.Domain.Models.TestCaseExecution", b =>
                {
                    b.HasOne("TesterLab.Domain.Models.TestCase", "TestCase")
                        .WithMany()
                        .HasForeignKey("TestCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TesterLab.Domain.Models.TestRun", "TestRun")
                        .WithMany()
                        .HasForeignKey("TestRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TestCase");

                    b.Navigation("TestRun");
                });

            modelBuilder.Entity("TesterLab.Domain.Models.TestData", b =>
                {
                    b.HasOne("TesterLab.Domain.Models.Application", "Application")
                        .WithMany("TestDataSets")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TesterLab.Domain.Models.Environment", "SpecificEnvironment")
                        .WithMany()
                        .HasForeignKey("SpecificEnvironmentId");

                    b.Navigation("Application");

                    b.Navigation("SpecificEnvironment");
                });

            modelBuilder.Entity("TesterLab.Domain.Models.TestRun", b =>
                {
                    b.HasOne("TesterLab.Domain.Models.Application", "Application")
                        .WithMany()
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TesterLab.Domain.Models.Environment", "Environment")
                        .WithMany()
                        .HasForeignKey("EnvironmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TesterLab.Domain.Models.TestData", "TestData")
                        .WithMany()
                        .HasForeignKey("TestDataId");

                    b.Navigation("Application");

                    b.Navigation("Environment");

                    b.Navigation("TestData");
                });

            modelBuilder.Entity("TesterLab.Domain.Models.TestStep", b =>
                {
                    b.HasOne("TesterLab.Domain.Models.TestCase", "TestCase")
                        .WithMany("TestSteps")
                        .HasForeignKey("TestCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TestCase");
                });

            modelBuilder.Entity("TesterLab.Domain.Models.TestStepExecution", b =>
                {
                    b.HasOne("TesterLab.Domain.Models.TestCaseExecution", "TestCaseExecution")
                        .WithMany("StepExecutions")
                        .HasForeignKey("TestCaseExecutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TesterLab.Domain.Models.TestStep", "TestStep")
                        .WithMany()
                        .HasForeignKey("TestStepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TestCaseExecution");

                    b.Navigation("TestStep");
                });

            modelBuilder.Entity("TesterLab.Domain.Models.Application", b =>
                {
                    b.Navigation("Environments");

                    b.Navigation("Features");

                    b.Navigation("TestDataSets");
                });

            modelBuilder.Entity("TesterLab.Domain.Models.Feature", b =>
                {
                    b.Navigation("TestCases");
                });

            modelBuilder.Entity("TesterLab.Domain.Models.TestCase", b =>
                {
                    b.Navigation("TestSteps");
                });

            modelBuilder.Entity("TesterLab.Domain.Models.TestCaseExecution", b =>
                {
                    b.Navigation("StepExecutions");
                });
#pragma warning restore 612, 618
        }
    }
}
